# OpenIaC: OpenStack Standalone Inventory Sample
[all:vars]
ansible_user=root

# ------------------------------------------------------------------------------
# 1. PHYSICAL NODES (OpenStack Dedicated Hardware)
# ------------------------------------------------------------------------------
[all_nodes]
controller-01 ansible_host=192.168.100.10
compute-01 ansible_host=192.168.100.20
compute-02 ansible_host=192.168.100.21

# ==============================================================================
# ☁️ LOGICAL TOPOLOGY (OpenStack)
# ==============================================================================
[os_controller]
controller-01

[os_compute]
compute-01
compute-02

[os_network]
controller-01

[openstack_cluster:children]
os_controller
os_compute
os_network
