[physical_nodes]
ceph-node1 ansible_host=192.168.60.11 ansible_user=vagrant ansible_ssh_private_key_file=../../../vagrant/ceph-cluster/.vagrant/machines/ceph-node1/virtualbox/private_key
ceph-node2 ansible_host=192.168.60.12 ansible_user=vagrant ansible_ssh_private_key_file=../../../vagrant/ceph-cluster/.vagrant/machines/ceph-node2/virtualbox/private_key
ceph-node3 ansible_host=192.168.60.13 ansible_user=vagrant ansible_ssh_private_key_file=../../../vagrant/ceph-cluster/.vagrant/machines/ceph-node3/virtualbox/private_key

[ceph_mons]
ceph-node1
ceph-node2
ceph-node3

[ceph_mgrs]
ceph-node1
ceph-node2
ceph-node3

[ceph_osds]
ceph-node1
ceph-node2
ceph-node3

[ceph:children]
ceph_mons
ceph_mgrs
ceph_osds
