# OpenIaC Sample Inventory

[all:vars]
ansible_user=root
# Flag to determine if installation is online or air-gapped
airgapped_mode=false 

[control_plane]
cp-01 ansible_host=192.168.100.10
cp-02 ansible_host=192.168.100.11
cp-03 ansible_host=192.168.100.12

[worker_nodes]
worker-01 ansible_host=192.168.100.20
worker-02 ansible_host=192.168.100.21

[k8s_cluster:children]
control_plane
worker_nodes

[openstack_compute]
worker-01
worker-02
