# OpenIaC: Unified (Multi-Solution) Inventory Sample
[all:vars]
ansible_user=root

# ------------------------------------------------------------------------------
# 1. PHYSICAL NODES (Baremetal/Virtual Machine List)
# ------------------------------------------------------------------------------
[all_nodes]
infra-01 ansible_host=192.168.100.10
infra-02 ansible_host=192.168.100.11
compute-01 ansible_host=192.168.100.20
compute-02 ansible_host=192.168.100.21

# ==============================================================================
# 🐳 KUBERNETES TOPOLOGY
# ==============================================================================
[k8s_control_plane]
infra-01

[k8s_workers]
compute-01
compute-02

[k8s_cluster:children]
k8s_control_plane
k8s_workers

# ==============================================================================
# ☁️ OPENSTACK TOPOLOGY
# ==============================================================================
[os_controller]
infra-01
infra-02

[os_compute]
compute-01
compute-02

[openstack_cluster:children]
os_controller
os_compute
