# OpenIaC: K3s Standalone Inventory Sample
[all:vars]
ansible_user=root

# ------------------------------------------------------------------------------
# 1. PHYSICAL NODES (K3s Dedicated Hardware)
# ------------------------------------------------------------------------------
[all_nodes]
cp-01 ansible_host=192.168.100.10
worker-01 ansible_host=192.168.100.20
worker-02 ansible_host=192.168.100.21

# ==============================================================================
# 🐳 LOGICAL TOPOLOGY (Kubernetes)
# ==============================================================================
[k8s_control_plane]
cp-01

[k8s_workers]
worker-01
worker-02

[k8s_cluster:children]
k8s_control_plane
k8s_workers
