---
# tasks file for base_os

- name: Ping the host
  ping:

- name: Disable Swap (Required for K8s)
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  tags: ['prep']

- name: Remove swap from fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
  tags: ['prep']

- name: Load necessary kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  tags: ['kernel']

- name: Disable firewalld (RedHat/Rocky)
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true
  when: ansible_os_family == "RedHat"

- name: Set SELinux to permissive (RedHat/Rocky)
  shell: |
    setenforce 0 || true
    sed -i 's/^SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config
  ignore_errors: true
  when: ansible_os_family == "RedHat"

- name: Disable UFW (Ubuntu/Debian)
  systemd:
    name: ufw
    state: stopped
    enabled: no
  ignore_errors: true
  when: ansible_os_family == "Debian"
